name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Ogni giorno a mezzanotte

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Generate stats image
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=emanueletocci&show_icons=true&count_private=true"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add stats.svg
          git commit -m "Aggiorna statistiche GitHub" || echo "Nessuna modifica da committare"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/emanueletocci/github-stats.git main

