name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Esegue il workflow ogni giorno a mezzanotte

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub stats
        uses: anuraghazra/github-readme-stats@v1
        with:
          token: ${{ secrets.GH_STATS_TOKEN }}
          username: emanueletocci
          count_private: true
          output_dir: stats

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add stats/*
          git commit -m "Aggiorna statistiche GitHub" || echo "Nessuna modifica da committare"
          git push
